### ISSUE TITLE
Add a LICENSE/COPYRIGHT file

### ISSUE THREAD

**Issue by reedy** [bbdoc/PoracleWeb#6]
:)

**Comment by bbdoc** [comment]
Solved with PR #8

**Comment by reedy** [comment]
Haha, no #8 doesn't solve this :)

You need to add a file called LICENSE or COPYRIGHT (or similar), with the appropriate contents, as per https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

And when you've chosen a license, we can update the license field of the composer.json

**Comment by bbdoc** [comment]
Ah ok misunderstood it 😁

**Comment by reedy** [comment]
Heh 😃

You're the author, so can choose the license. I'm happy (as I think the only other author atm) to retrospectively "license" my couple of changes so far under most of the open source standard licenses

**Comment by bbdoc** [comment]
Licence file added.
